steps:
  - command:
    - apk update
    - apk add terraform

  - wait

  - command: terraform init -input=false

  - wait

  - command: test.sh

  - wait

  - command: set-tf-vars.sh
  - command:
    - buildkite-agent artifact download bk.tfvars .
    - terraform plan -input=false -var-file=bk.tfvars

  - command: echo finished