steps:
  - command: apk update
  - command: apk add terraform

  - wait

  - command: terraform init -input=false

  - wait

  - command: test.sh

  - wait

  - command: terraform plan -input=false

  - command: echo finished