steps:
  - command:
    - apk update
    - apk add terraform

  - wait

  - command: terraform init -input=false

  - wait

  - command: test.sh

  - wait

  - command: set-tf-vars.sh
  - label: Terraform Plan
    command:
      - buildkite-agent artifact download bk.tfvars .
      - terraform plan -input=false -var-file=bk.tfvars

  - wait

  - block: Deploy?

  - label: Terraform Apply
    command:
      - buildkite-agent artifact download bk.tfvars .
      - terraform apply -input=false -var-file=bk.tfvars

  - command: echo finished