steps:
  - label: Terraform Init
    command:
      - terraform-init.sh

  - wait

  - block: Terraform Command
    fields:
      - select: "Command"
        key: "terraform-command"
        options:
          - label: "Apply"
            value: "apply"
          - label: "Destroy"
            value: "destroy"
          - label: "Refresh"
            value: "refresh"

  - wait

  - label: Terraform Plan
    command:
      - terraform plan -input=false -out=bkplan.tfplan
      - buildkite-agent artifact upload bkplan.tfplan

  - wait

  - block: Run Terraform?

  - label: Run Terraform
    command:
      - terraform-run.sh