steps:
  - command:
    - apk update
    - apk add terraform

  - wait

  - command: terraform init -input=false

  - wait

  - command: test.sh

  - wait

  - command: set-tf-vars.sh
  - command: terraform plan -input=false

  - command: echo finished