steps:
  - label: Terraform Init
    command:
      - apk add terraform --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community
      - az login --msi
      - terraform init -input=false

  - wait

  - block: Terraform Command
    fields:
      - select: "Command"
        key: "terraform-command"
        options:
          - label: "Apply"
            value: "apply"
          - label: "Destroy"
            value: "destroy"
          - label: "Refresh"
            value: "refresh"

  - wait

  - label: Terraform Plan
    command:
      - az login --msi
      - ls -a $HOME/.azure
      - terraform init -input=false
      - terraform plan -input=false -out=bkplan.tfplan
      - buildkite-agent artifact upload bkplan.tfplan

  - wait

  - block: Run Terraform?

  - label: Run Terraform
    command:
      - run-terraform.sh