steps:
  - label: Terraform Init
    command:
      - apk add terraform --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community
      - TOKEN=$(curl http://localhost:50342/oauth2/token --data "resource=https://management.azure.com/" -H Metadata:true -s)
      - mkdir -p $HOME/.azure
      - echo "[$TOKEN]" > $HOME/.azure/accessTokens.json
      - terraform init -input=false

  - wait

  - block: Terraform Command
    fields:
      - select: "Command"
        key: "terraform-command"
        options:
          - label: "Apply"
            value: "apply"
          - label: "Destroy"
            value: "destroy"
          - label: "Refresh"
            value: "refresh"

  - wait

  - label: Terraform Plan
    command:
      - terraform plan -input=false -out=bkplan.tfplan
      - buildkite-agent artifact upload bkplan.tfplan

  - wait

  - block: Run Terraform?

  - label: Run Terraform
    command:
      - run-terraform.sh