env:
  ARM_USE_MSI: true
  TF_PLUGIN_CACHE_DIR: "$HOME/.terraform.d/plugin-cache"
  ARM_MSI_ENDPOINT: http://localhost:50342/oauth2/token
steps:
  - label: Terraform Init
    command:
      - terraform-init.sh

  - wait

  - block: Terraform Command
    fields:
      - select: "Command"
        key: "terraform-command"
        options:
          - label: "Apply"
            value: "apply"
          - label: "Destroy"
            value: "destroy"
          - label: "Refresh"
            value: "refresh"

  - wait

  - label: Terraform Plan
    command:
      - terraform-plan.sh

  - wait

  - block: Run Terraform?

  - label: Run Terraform
    command:
      - terraform-run.sh